<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Model\Composition;

/**
 * Action Class Doc Comment.
 *
 * @category Class
 *
 * @description Type of Composition Batch operation.
 *
 * @license MIT
 * Modified by WebDevStudios on 27-May-2026 using Strauss.
 * @see https://github.com/BrianHenryIE/strauss
 */
class Action
{
    /**
     * Possible values of this enum.
     */
    public const UPSERT = 'upsert';

    public const DELETE = 'delete';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UPSERT,
            self::DELETE,
        ];
    }
}
