<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Model\Search;

/**
 * CategoryPredictionBin Class Doc Comment.
 *
 * @category Class
 *
 * @description Confidence level of the category prediction.
 *
 * @license MIT
 * Modified by WebDevStudios on 27-May-2026 using Strauss.
 * @see https://github.com/BrianHenryIE/strauss
 */
class CategoryPredictionBin
{
    /**
     * Possible values of this enum.
     */
    public const CERTAIN = 'certain';

    public const VERY_HIGH = 'very high';

    public const HIGH = 'high';

    public const LOW = 'low';

    public const VERY_LOW = 'very low';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CERTAIN,
            self::VERY_HIGH,
            self::HIGH,
            self::LOW,
            self::VERY_LOW,
        ];
    }
}
