<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Model\Search;

/**
 * DictionaryEntryType Class Doc Comment.
 *
 * @category Class
 *
 * @description Whether a dictionary entry is provided by Algolia (standard), or has been added by you (custom).
 *
 * @license MIT
 * Modified by WebDevStudios on 27-May-2026 using Strauss.
 * @see https://github.com/BrianHenryIE/strauss
 */
class DictionaryEntryType
{
    /**
     * Possible values of this enum.
     */
    public const CUSTOM = 'custom';

    public const STANDARD = 'standard';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CUSTOM,
            self::STANDARD,
        ];
    }
}
