<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Model\Search;

/**
 * QueryCategorizationType Class Doc Comment.
 *
 * @category Class
 *
 * @description Classification of the query scope.
 *
 * @license MIT
 * Modified by WebDevStudios on 27-May-2026 using Strauss.
 * @see https://github.com/BrianHenryIE/strauss
 */
class QueryCategorizationType
{
    /**
     * Possible values of this enum.
     */
    public const NARROW = 'narrow';

    public const BROAD = 'broad';

    public const AMBIGUOUS = 'ambiguous';

    public const NONE = 'none';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NARROW,
            self::BROAD,
            self::AMBIGUOUS,
            self::NONE,
        ];
    }
}
