<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Model\Recommend;

/**
 * AroundRadiusAll Class Doc Comment.
 *
 * @category Class
 *
 * @description Return all records with a valid `_geoloc` attribute. Don't filter by distance.
 *
 * @license MIT
 * Modified by WebDevStudios on 27-May-2026 using Strauss.
 * @see https://github.com/BrianHenryIE/strauss
 */
class AroundRadiusAll
{
    /**
     * Possible values of this enum.
     */
    public const ALL = 'all';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ALL,
        ];
    }
}
