<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Model\Recommend;

/**
 * MatchLevel Class Doc Comment.
 *
 * @category Class
 *
 * @description Whether the whole query string matches or only a part.
 *
 * @license MIT
 * Modified by WebDevStudios on 27-May-2026 using Strauss.
 * @see https://github.com/BrianHenryIE/strauss
 */
class MatchLevel
{
    /**
     * Possible values of this enum.
     */
    public const NONE = 'none';

    public const PARTIAL = 'partial';

    public const FULL = 'full';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::PARTIAL,
            self::FULL,
        ];
    }
}
