<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Model\Ingestion;

/**
 * ActionType Class Doc Comment.
 *
 * @category Class
 *
 * @description Action to perform on the Algolia index.
 *
 * @license MIT
 * Modified by WebDevStudios on 27-May-2026 using Strauss.
 * @see https://github.com/BrianHenryIE/strauss
 */
class ActionType
{
    /**
     * Possible values of this enum.
     */
    public const REPLACE = 'replace';

    public const SAVE = 'save';

    public const PARTIAL = 'partial';

    public const PARTIAL_NO_CREATE = 'partialNoCreate';

    public const APPEND = 'append';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::REPLACE,
            self::SAVE,
            self::PARTIAL,
            self::PARTIAL_NO_CREATE,
            self::APPEND,
        ];
    }
}
