<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Model\Ingestion;

/**
 * DockerStreamsSyncMode Class Doc Comment.
 *
 * @category Class
 *
 * @description The strategy to use to fetch the data.
 *
 * @license MIT
 * Modified by WebDevStudios on 27-May-2026 using Strauss.
 * @see https://github.com/BrianHenryIE/strauss
 */
class DockerStreamsSyncMode
{
    /**
     * Possible values of this enum.
     */
    public const INCREMENTAL = 'incremental';

    public const FULL_TABLE = 'fullTable';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INCREMENTAL,
            self::FULL_TABLE,
        ];
    }
}
