<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Model\Ingestion;

/**
 * EntityType Class Doc Comment.
 *
 * @category Class
 *
 * @description Type of entity to update.
 *
 * @license MIT
 * Modified by WebDevStudios on 27-May-2026 using Strauss.
 * @see https://github.com/BrianHenryIE/strauss
 */
class EntityType
{
    /**
     * Possible values of this enum.
     */
    public const PRODUCT = 'product';

    public const COLLECTION = 'collection';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PRODUCT,
            self::COLLECTION,
        ];
    }
}
