<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Model\Ingestion;

/**
 * MappingFormatSchema Class Doc Comment.
 *
 * @category Class
 *
 * @description Mapping format schema.
 *
 * @license MIT
 * Modified by WebDevStudios on 27-May-2026 using Strauss.
 * @see https://github.com/BrianHenryIE/strauss
 */
class MappingFormatSchema
{
    /**
     * Possible values of this enum.
     */
    public const MAPPINGKIT_V1 = 'mappingkit/v1';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MAPPINGKIT_V1,
        ];
    }
}
