<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Model\Ingestion;

/**
 * RunOutcome Class Doc Comment.
 *
 * @category Class
 *
 * @description Task run outcome.
 *
 * @license MIT
 * Modified by WebDevStudios on 27-May-2026 using Strauss.
 * @see https://github.com/BrianHenryIE/strauss
 */
class RunOutcome
{
    /**
     * Possible values of this enum.
     */
    public const SUCCESS = 'success';

    public const FAILURE = 'failure';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SUCCESS,
            self::FAILURE,
        ];
    }
}
