<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Model\Ingestion;

/**
 * RunReasonCode Class Doc Comment.
 *
 * @category Class
 *
 * @description A code for the task run's outcome. A readable description of the code is included in the `reason` response property.
 *
 * @license MIT
 * Modified by WebDevStudios on 27-May-2026 using Strauss.
 * @see https://github.com/BrianHenryIE/strauss
 */
class RunReasonCode
{
    /**
     * Possible values of this enum.
     */
    public const INTERNAL = 'internal';

    public const CANCELLED = 'cancelled';

    public const CRITICAL = 'critical';

    public const NO_EVENTS = 'no_events';

    public const TOO_MANY_ERRORS = 'too_many_errors';

    public const LACKING_EVENTS = 'lacking_events';

    public const OK = 'ok';

    public const BLOCKING = 'blocking';

    public const IDLE = 'idle';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INTERNAL,
            self::CANCELLED,
            self::CRITICAL,
            self::NO_EVENTS,
            self::TOO_MANY_ERRORS,
            self::LACKING_EVENTS,
            self::OK,
            self::BLOCKING,
            self::IDLE,
        ];
    }
}
