<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Model\Ingestion;

/**
 * RunType Class Doc Comment.
 *
 * @category Class
 *
 * @description Task run type.
 *
 * @license MIT
 * Modified by WebDevStudios on 27-May-2026 using Strauss.
 * @see https://github.com/BrianHenryIE/strauss
 */
class RunType
{
    /**
     * Possible values of this enum.
     */
    public const REINDEX = 'reindex';

    public const UPDATE = 'update';

    public const DISCOVER = 'discover';

    public const VALIDATE = 'validate';

    public const PUSH = 'push';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::REINDEX,
            self::UPDATE,
            self::DISCOVER,
            self::VALIDATE,
            self::PUSH,
        ];
    }
}
