<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Model\Ingestion;

/**
 * SourceType Class Doc Comment.
 *
 * @category Class
 *
 * @license MIT
 * Modified by WebDevStudios on 27-May-2026 using Strauss.
 * @see https://github.com/BrianHenryIE/strauss
 */
class SourceType
{
    /**
     * Possible values of this enum.
     */
    public const ALGOLIA_INDEX = 'algoliaIndex';

    public const BIGCOMMERCE = 'bigcommerce';

    public const BIGQUERY = 'bigquery';

    public const COMMERCETOOLS = 'commercetools';

    public const CSV = 'csv';

    public const DOCKER = 'docker';

    public const GA4_BIGQUERY_EXPORT = 'ga4BigqueryExport';

    public const JSON = 'json';

    public const SHOPIFY = 'shopify';

    public const PUSH = 'push';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ALGOLIA_INDEX,
            self::BIGCOMMERCE,
            self::BIGQUERY,
            self::COMMERCETOOLS,
            self::CSV,
            self::DOCKER,
            self::GA4_BIGQUERY_EXPORT,
            self::JSON,
            self::SHOPIFY,
            self::PUSH,
        ];
    }
}
