<?php

// autoload-files.php @generated by Strauss
// @see https://github.com/BrianHenryIE/strauss/

require_once __DIR__ . '/algolia/algoliasearch-client-php/lib/Http/Psr7/functions.php';
require_once __DIR__ . '/ralouphie/getallheaders/src/getallheaders.php';
