<?php

// autoload-files.php @generated by Strauss
// @see https://github.com/BrianHenryIE/strauss/

require_once __DIR__ . '/algolia/algoliasearch-client-php/src/Http/Psr7/functions.php';
require_once __DIR__ . '/algolia/algoliasearch-client-php/src/functions.php';
