<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

namespace WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Model\Monitoring;

/**
 * Status Class Doc Comment.
 *
 * @category Class
 *
 * @description Status of the cluster.
 *
 * @license MIT
 * Modified by WebDevStudios on 27-May-2026 using Strauss.
 * @see https://github.com/BrianHenryIE/strauss
 */
class Status
{
    /**
     * Possible values of this enum.
     */
    public const OPERATIONAL = 'operational';

    public const DEGRADED_PERFORMANCE = 'degraded_performance';

    public const PARTIAL_OUTAGE = 'partial_outage';

    public const MAJOR_OUTAGE = 'major_outage';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OPERATIONAL,
            self::DEGRADED_PERFORMANCE,
            self::PARTIAL_OUTAGE,
            self::MAJOR_OUTAGE,
        ];
    }
}
